FROM zegarson-dev

ENV STM32CUBEIDE_VERSION=1.16.0
ENV DEBIAN_FRONTEND=noninteractive
ENV LICENSE_ALREADY_ACCEPTED=1
ENV PATH="${PATH}:/opt/st/stm32cubeide_${STM32CUBEIDE_VERSION}"

COPY en.st-stm32cubeide_1.16.0_21983_20240628_1741_amd64.deb_bundle.sh.zip /tmp/stm32cubeide-installer.sh.zip

RUN sudo su && unzip -p /tmp/stm32cubeide-installer.sh.zip > /tmp/stm32cubeide-installer.sh

RUN sudo chmod +x /tmp/stm32cubeide-installer.sh
RUN sudo LICENSE_ALREADY_ACCEPTED=1 DEBIAN_FRONTEND=noninteractive /tmp/stm32cubeide-installer.sh

RUN sudo apt-get -y -f install
RUN echo ""

CMD ["/bin/bash"]